title: Space Shooter
description: 2D Unity Space Shooter
theme: just-the-docs
gems: [jekyll-mermaid]

url: https://spaceshooter.captaincoder.org/

# aux_links:
#   Google Classroom: https://classroom.google.com/

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue
  funfact:
    title: "Fun Fact"
    color: blue